import { FaMale, FaFemale } from "react-icons/fa";

export const categories = [
  "Allergist",
  "Anesthesiologist",
  "Cardiologist",
  "Dermatologist",
  "Endocrinologist",
  "Gastroenterologist",
  "Geriatrician",
  "Hematologist",
  "Infectious Disease Specialist",
  "Internist",
  "Neonatologist",
  "Nephrologist",
  "Neurologist",
  "Obstetrician",
  "Gynecologist",
  "Oncologist",
  "Ophthalmologist",
  "Orthopedic Surgeon",
  "Otolaryngologist (ENT Specialist)",
  "Pathologist",
  "Pediatrician",
  "Physiatrist (Physical Medicine and Rehabilitation)",
  "Plastic Surgeon",
  "Psychiatrist",
  "Pulmonologist",
  "Radiologist",
  "Rheumatologist",
  "Sports Medicine Specialist",
  "Surgeon",
  "Thoracic Surgeon",
  "Urologist",
  "Vascular Surgeon",
];

export const doctors = [
  {
    id: 1,
    name: "Dr. Sarah Lee",
    appointmentTime: "9:00 AM - 12:00 PM",
    fees: 150,
    category: "Dermatologist",
    hospital: "City Skin Clinic",
    gender: "Female",
    genderIcon: <FaFemale />,
  },
  {
    id: 2,
    name: "Dr. John Smith",
    appointmentTime: "1:00 PM - 5:00 PM",
    fees: 200,
    category: "Cardiologist",
    hospital: "Heart Care Hospital",
    gender: "Male",
    genderIcon: <FaMale />,
  },
  {
    id: 3,
    name: "Dr. Emily Chen",
    appointmentTime: "10:00 AM - 4:00 PM",
    fees: 180,
    category: "Pediatrician",
    hospital: "Bright Kids Hospital",
    gender: "Female",
    genderIcon: <FaFemale />,
  },
  {
    id: 4,
    name: "Dr. Michael Brown",
    appointmentTime: "8:00 AM - 11:00 AM",
    fees: 220,
    category: "Orthopedic Surgeon",
    hospital: "Advanced Orthopedics Center",
    gender: "Male",
    genderIcon: <FaMale />,
  },
  {
    id: 5,
    name: "Dr. Rachel Patel",
    appointmentTime: "11:00 AM - 3:00 PM",
    fees: 250,
    category: "Oncologist",
    hospital: "Cancer Care Institute",
    gender: "Female",
    genderIcon: <FaFemale />,
  },
  {
    id: 6,
    name: "Dr. Ahmed Khan",
    appointmentTime: "2:00 PM - 6:00 PM",
    fees: 300,
    category: "Neurologist",
    hospital: "Brain and Spine Hospital",
    gender: "Male",
    genderIcon: <FaMale />,
  },
  {
    id: 7,
    name: "Dr. Linda Martinez",
    appointmentTime: "9:00 AM - 1:00 PM",
    fees: 130,
    category: "Gynecologist",
    hospital: "Women's Health Clinic",
    gender: "Female",
    genderIcon: <FaFemale />,
  },
  {
    id: 8,
    name: "Dr. Raj Singh",
    appointmentTime: "12:00 PM - 4:00 PM",
    fees: 160,
    category: "Endocrinologist",
    hospital: "Diabetes and Hormone Center",
    gender: "Male",
    genderIcon: <FaMale />,
  },
  {
    id: 9,
    name: "Dr. Maria Gonzalez",
    appointmentTime: "3:00 PM - 7:00 PM",
    fees: 210,
    category: "Pulmonologist",
    hospital: "Respiratory Health Clinic",
    gender: "Female",
    genderIcon: <FaFemale />,
  },
  {
    id: 10,
    name: "Dr. William Thompson",
    appointmentTime: "7:00 AM - 10:00 AM",
    fees: 175,
    category: "Ophthalmologist",
    hospital: "Vision Care Center",
    gender: "Male",
    genderIcon: <FaMale />,
  },
  {
    id: 11,
    name: "Dr. Sarah Lee",
    appointmentTime: "9:00 AM - 12:00 PM",
    fees: 150,
    category: "Dermatologist",
    hospital: "City Skin Clinic",
    gender: "Female",
    genderIcon: <FaFemale />,
  },
  {
    id: 12,
    name: "Dr. John Smith",
    appointmentTime: "1:00 PM - 5:00 PM",
    fees: 200,
    category: "Cardiologist",
    hospital: "Heart Care Hospital",
    gender: "Male",
    genderIcon: <FaMale />,
  },
  {
    id: 13,
    name: "Dr. Emily Chen",
    appointmentTime: "10:00 AM - 4:00 PM",
    fees: 180,
    category: "Pediatrician",
    hospital: "Bright Kids Hospital",
    gender: "Female",
    genderIcon: <FaFemale />,
  },
  {
    id: 14,
    name: "Dr. Michael Brown",
    appointmentTime: "8:00 AM - 11:00 AM",
    fees: 220,
    category: "Orthopedic Surgeon",
    hospital: "Advanced Orthopedics Center",
    gender: "Male",
    genderIcon: <FaMale />,
  },
  {
    id: 15,
    name: "Dr. Rachel Patel",
    appointmentTime: "11:00 AM - 3:00 PM",
    fees: 250,
    category: "Oncologist",
    hospital: "Cancer Care Institute",
    gender: "Female",
    genderIcon: <FaFemale />,
  },
  {
    id: 16,
    name: "Dr. Ahmed Khan",
    appointmentTime: "2:00 PM - 6:00 PM",
    fees: 300,
    category: "Neurologist",
    hospital: "Brain and Spine Hospital",
    gender: "Male",
    genderIcon: <FaMale />,
  },
  {
    id: 17,
    name: "Dr. Linda Martinez",
    appointmentTime: "9:00 AM - 1:00 PM",
    fees: 130,
    category: "Gynecologist",
    hospital: "Women's Health Clinic",
    gender: "Female",
    genderIcon: <FaFemale />,
  },
  {
    id: 18,
    name: "Dr. Raj Singh",
    appointmentTime: "12:00 PM - 4:00 PM",
    fees: 160,
    category: "Endocrinologist",
    hospital: "Diabetes and Hormone Center",
    gender: "Male",
    genderIcon: <FaMale />,
  },
  {
    id: 19,
    name: "Dr. Maria Gonzalez",
    appointmentTime: "3:00 PM - 7:00 PM",
    fees: 210,
    category: "Pulmonologist",
    hospital: "Respiratory Health Clinic",
    gender: "Female",
    genderIcon: <FaFemale />,
  },
  {
    id: 20,
    name: "Dr. William Thompson",
    appointmentTime: "7:00 AM - 10:00 AM",
    fees: 175,
    category: "Ophthalmologist",
    hospital: "Vision Care Center",
    gender: "Male",
    genderIcon: <FaMale />,
  },
];

export const currentUser = {
  name: "Bilal",
  role: "doctor",
  email: "bilal@gamil.com",
};

export const appointments = [
  {
    user: {
      name: "John Doe",
      email: "johndoe@example.com",
    },
    appointmentTime: "10:30 AM",
    status: "confirmed",
    appointmentDate: "2024-11-15",
    doctor: {
      name: "Dr. Emily Carter",
      hospital: "City Health Hospital",
    },
  },
  {
    user: {
      name: "Sarah Lee",
      email: "sarah.lee@example.com",
    },
    appointmentTime: "1:00 PM",
    status: "pending",
    appointmentDate: "2024-11-16",
    doctor: {
      name: "Dr. Mark Thompson",
      hospital: "Downtown Clinic",
    },
  },
  {
    user: {
      name: "Michael Johnson",
      email: "michael.johnson@example.com",
    },
    appointmentTime: "9:00 AM",
    status: "confirmed",
    appointmentDate: "2024-11-18",
    doctor: {
      name: "Dr. Aisha Patel",
      hospital: "Green Valley Hospital",
    },
  },
  {
    user: {
      name: "Emma Watson",
      email: "emma.watson@example.com",
    },
    appointmentTime: "3:30 PM",
    status: "cancelled",
    appointmentDate: "2024-11-20",
    doctor: {
      name: "Dr. Liam Evans",
      hospital: "Westside Medical Center",
    },
  },
  {
    user: {
      name: "David Kim",
      email: "david.kim@example.com",
    },
    appointmentTime: "11:45 AM",
    status: "confirmed",
    appointmentDate: "2024-11-21",
    doctor: {
      name: "Dr. Sophia Nguyen",
      hospital: "Harmony Health Clinic",
    },
  },
  {
    user: {
      name: "Olivia Brown",
      email: "olivia.brown@example.com",
    },
    appointmentTime: "2:00 PM",
    status: "pending",
    appointmentDate: "2024-11-22",
    doctor: {
      name: "Dr. James Lee",
      hospital: "Maple Leaf Hospital",
    },
  },
  {
    user: {
      name: "Ethan Green",
      email: "ethan.green@example.com",
    },
    appointmentTime: "10:00 AM",
    status: "confirmed",
    appointmentDate: "2024-11-23",
    doctor: {
      name: "Dr. Linda Wilson",
      hospital: "Oceanview Health Center",
    },
  },
  {
    user: {
      name: "Sophia Turner",
      email: "sophia.turner@example.com",
    },
    appointmentTime: "4:15 PM",
    status: "rescheduled",
    appointmentDate: "2024-11-25",
    doctor: {
      name: "Dr. Michael Chan",
      hospital: "Sunrise Clinic",
    },
  },
  {
    user: {
      name: "Daniel Harris",
      email: "daniel.harris@example.com",
    },
    appointmentTime: "8:30 AM",
    status: "confirmed",
    appointmentDate: "2024-11-27",
    doctor: {
      name: "Dr. Olivia Garcia",
      hospital: "Unity Medical Center",
    },
  },
  {
    user: {
      name: "Ava Martinez",
      email: "ava.martinez@example.com",
    },
    appointmentTime: "12:30 PM",
    status: "cancelled",
    appointmentDate: "2024-11-29",
    doctor: {
      name: "Dr. Richard Adams",
      hospital: "Northside Health Clinic",
    },
  },
];
